### ISSUE TITLE
Add-on failed to start after 1.1.3 update.

### ISSUE THREAD

**Issue by Sjeff** [helto4real/hassio-add-ons#9]
The add-on doesn't start after updating to the latest version 1.1.3 via the add-on store

error in the home assistant supervisor : 
```
ERROR (SyncWorker_14) [hassio.docker] Can't create container from addon_1e72b768_better_presence: 404 Client Error: Not Found ("No such image: helto4real/hassio-better-presence-amd64:1.1.3")
```

Running hassio on intel nuc:
hassio: 0.102.1
supervisor: 192

no issue's with the previous version.

Revert back to version 1.1.2 via snapshot.

**Comment by raffaelevall** [comment]
I have the same issue on raspberry pi3B+, docker.

hassio: 0.102.1
supervisor: 192

Snapshot restored

**Comment by jumping2000** [comment]
I also have problem with the 1.1.3 upgrade:
hass,io 0.102.2
supervisor 192

19-11-25 17:39:27 INFO (SyncWorker_1) [hassio.docker.interface] Update image 1e72b768/amd64-addon-better_presence:1.1.1 to helto4real/hassio-better-presence-amd64:1.1.3
19-11-25 17:39:27 INFO (SyncWorker_1) [hassio.docker.addon] Start build 1e72b768/amd64-addon-better_presence:1.1.3
19-11-25 17:39:55 ERROR (SyncWorker_1) [hassio.docker.addon] Can't build 1e72b768/amd64-addon-better_presence:1.1.3: The command '/bin/ash -o pipefail -c apk update &&     apk add --no-cache git make musl-dev go' returned a non-zero code: 5

**Comment by TriptonPt** [comment]
Same issue here !

This error comes up in the log : 

[FATAL tini (8)] exec /init failed: Exec format error

**Comment by ThePirat91** [comment]
> 
> 
> Same issue here !
> 
> This error comes up in the log :
> 
> [FATAL tini (8)] exec /init failed: Exec format error

Same error here with 1.1.3 on hassio (via docker on rpi3b+).
HA version 0.102.2

**Comment by septeven** [comment]
Same thing here, any chance to get it fixed soon ?

**Comment by helto4real** [comment]
Try uninstall and reinstall. This has worked for amd64 platforms at least. Something seems broken with RPI image. Will revert to old version until it is fixed.

**Comment by helto4real** [comment]
Reverted back to locally built add-on, please uninstall and reinstall to the new 1.1.4 image if you have problems. **Remember to copy the settings before uninstalling!!** Let me know if you still have problems.

**Comment by helto4real** [comment]
Soon post a more permanent fix (hopefully)

**Comment by Sjeff** [comment]
Thanks @helto4real.

Fixed after updating to 1.1.4.

**Comment by TriptonPt** [comment]
@Sjeff where are you seeing 1.1.4 ?? I reinstalled, it's still version 1.1.3 and the issue remains

**Comment by Sjeff** [comment]
@TriptonPt Did you refresh the addon store?
![image](https://user-images.githubusercontent.com/11430228/69829560-c74a2500-1220-11ea-9ffe-cd2b7b2fa2b9.png)

**Comment by TriptonPt** [comment]
@Sjeff indeed I hadn't !! Fixed now, thanks !! :)

**Comment by raffaelevall** [comment]
Many tks fixed 😉😉😉

**Comment by ThePirat91** [comment]
Fixed...many thanks! 👍

**Comment by jumping2000** [comment]
For me it's not fixed:

19-12-02 13:28:41 INFO (SyncWorker_9) [hassio.docker.addon] Start build 1e72b768/amd64-addon-better_presence:1.1.4
19-12-02 13:29:09 ERROR (SyncWorker_9) [hassio.docker.addon] Can't build 1e72b768/amd64-addon-better_presence:1.1.4: The command '/bin/ash -o pipefail -c apk update &&     apk add --no-cache git make musl-dev go' returned a non-zero code: 5

**Comment by helto4real** [comment]
> For me it's not fixed:
> 
> 19-12-02 13:28:41 INFO (SyncWorker_9) [hassio.docker.addon] Start build 1e72b768/amd64-addon-better_presence:1.1.4
> 19-12-02 13:29:09 ERROR (SyncWorker_9) [hassio.docker.addon] Can't build 1e72b768/amd64-addon-better_presence:1.1.4: The command '/bin/ash -o pipefail -c apk update && apk add --no-cache git make musl-dev go' returned a non-zero code: 5

Did you try to unistall the whole add-on and reinstall it? Also remember to copy old settings before removing it.

**Comment by helto4real** [comment]
I am doing a new release but need help testing. Copy the presence folder from this link
https://github.com/helto4real/hassio-add-ons/tree/rel_1_2 to local addons folder
Copy settings from old one before uninstall it and add the local one. It should be version 1.2 if correct. Let me know if it works for you please before I release it. Let me know here. Also say if you have ARM based or Amd64 based device.

**Comment by Sjeff** [comment]
@helto4real 
Dev environment:
  Raspberry Pi 3b (ARM) running the local 1.2.0 version.
  looks like its working have to check if the devices update when i get home this afternoon.

config:
```
{
  "log_level": "info",
  "tracking": {
    "just_arrived_time": 300,
    "just_left_time": 60,
    "home_state": "Home",
    "just_left_state": "Just Left",
    "just_arrived_state": "Just Arrived",
    "away_state": "Away"
  },
  "persons": [
    {
      "id": "test",
      "friendly_name": "test",
      "devices": [
        "device_tracker.wifi",
        "device_tracker.gps",
        "sensor.bluetooth"
      ]
    }
  ]
}
```

Main environment:
  Intel NUC (Amd64) running latest 1.1.4 version.
  Working as intended.

config:
```
{
  "log_level": "info",
  "tracking": {
    "just_arrived_time": 300,
    "just_left_time": 60,
    "home_state": "Home",
    "just_left_state": "Just Left",
    "just_arrived_state": "Just Arrived",
    "away_state": "Away"
  },
  "persons": [
    {
      "id": "person1",
      "friendly_name": "person1",
      "devices": [
        "device_tracker.person1_gps",
        "device_tracker.person1_wifi",
        "sensor.person1_bluetooth"
      ]
    },
    {
      "id": "person2",
      "friendly_name": "person2",
      "devices": [
        "device_tracker.person2_gps",
        "device_tracker.person2_wifi",
        "sensor.person2_bluetooth"
      ]
    }
  ]
}
```

**Comment by helto4real** [comment]
Thanks @Sjeff for testing this out. I'm really grateful

**Comment by helto4real** [comment]
I will release the version 1.2 now officially and let men know if there is any problems with it. You guys migt need to uninstall the old verison before install this one. **remember to copy settings before uninstalling**
